# Generated by Django 4.2.6 on 2023-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="user bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_open_to_collab",
            field=models.BooleanField(default=True, verbose_name="user is open to collaboration"),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.CharField(blank=True, max_length=100, verbose_name="link to user's linkedin url"),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="user_skills", to="projects.skill", verbose_name="user's skills"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.CharField(blank=True, max_length=100, verbose_name="link to user's twitter profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, verbose_name="Username of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.TextField(blank=True, verbose_name="link to user's personal website"),
        ),
    ]
