# Generated by Django 4.2.6 on 2023-10-23 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_tags_remove_project_tags_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
    ]
